import { Role } from '@/auth/roles';

export type AppScreenKey =
  | 'dashboard'
  | 'chamas_list'
  | 'chama_details'
  | 'members'
  | 'contributions'
  | 'finance'
  | 'payments'
  | 'loans'
  | 'meetings'
  | 'governance'
  | 'announcements'
  | 'notifications'
  | 'reports'
  | 'profile'
  | 'settings'
  | 'support'
  | 'ai_assistant';

export interface ScreenRoleExperience {
  visible: boolean;
  access: 'full' | 'limited' | 'read_only' | 'self_service' | 'support' | 'inspect_only';
  scope: 'platform' | 'chama' | 'personal' | 'investigation';
  backendScope:
    | 'platform_all'
    | 'platform_moderation'
    | 'platform_support'
    | 'scoped_chama'
    | 'own_records'
    | 'investigation_only';
  sees: string[];
  does: string[];
  widgets?: string[];
  tabs?: string[];
  filters?: string[];
  quickActions?: string[];
}

type ScreenMatrix = Record<AppScreenKey, Record<Role, ScreenRoleExperience>>;

const exp = (experience: ScreenRoleExperience): ScreenRoleExperience => experience;

export const SCREEN_RBAC_MATRIX: ScreenMatrix = {
  dashboard: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['platform KPIs', 'provider health', 'failed jobs', 'fraud flags', 'global analytics'],
      does: ['Inspect provider failures and platform issues.', 'Review risk cases and system-wide operations.'],
      widgets: ['users', 'chamas', 'support backlog', 'risk alerts'],
      quickActions: ['Open failed jobs', 'Review fraud flags', 'Manage users'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['support tickets', 'moderation items', 'disputes', 'operational alerts'],
      does: ['Resolve tickets and moderation cases.', 'Send platform communications and review flagged cases.'],
      widgets: ['tickets', 'disputes', 'alerts'],
      quickActions: ['Resolve ticket', 'Review flagged chama'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['chama health', 'pending approvals', 'join requests', 'overdue contributions', 'upcoming meetings'],
      does: ['Approve requests, invite members, and open operational queues.'],
      widgets: ['health score', 'pending approvals', 'alerts'],
      quickActions: ['Invite members', 'Approve request', 'Create announcement'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['payment verifications', 'contribution compliance', 'liquidity summary', 'reconciliation alerts'],
      does: ['Verify payments and open finance queues.', 'Export finance-heavy reports.'],
      widgets: ['verifications', 'liquidity', 'reconciliation'],
      quickActions: ['Verify payment', 'Resolve reconciliation'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['upcoming meetings', 'attendance trends', 'minutes tasks', 'communication reminders'],
      does: ['Create meetings, record minutes, and send reminders.'],
      widgets: ['meeting queue', 'attendance alerts', 'announcement tasks'],
      quickActions: ['Create meeting', 'Record minutes', 'Post announcement'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['compliance widgets', 'read-only finance summaries', 'audit alerts', 'role changes'],
      does: ['Open audit logs and review compliance reports.'],
      widgets: ['compliance', 'audit alerts', 'defaults'],
      quickActions: ['Open audit log', 'Review compliance report'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['next contribution', 'overdue items', 'active loan summary', 'next meeting', 'announcements'],
      does: ['Pay contributions, request loans, and open meetings.'],
      widgets: ['due items', 'loan summary', 'notifications'],
      quickActions: ['Pay contribution', 'Request loan', 'Open meeting'],
    }),
  },
  chamas_list: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['all chamas', 'activity levels', 'risk flags'],
      does: ['Inspect and moderate chamas platform-wide.'],
      filters: ['status', 'risk', 'activity'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_moderation',
      sees: ['moderated chamas', 'flagged chamas'],
      does: ['Review and moderate problematic chamas.'],
      filters: ['flagged', 'support-needed'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['managed chamas', 'role badges', 'health indicators'],
      does: ['Open and manage relevant chama workspaces.'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['finance status indicators for assigned chamas'],
      does: ['Open finance-relevant chama workspaces.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['meeting and governance indicators for assigned chamas'],
      does: ['Open meeting-related chama workspaces.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['audited chamas', 'review indicators'],
      does: ['Open read-only review workspaces.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['joined chamas', 'role badge', 'basic status'],
      does: ['Open a chama or switch the current workspace.'],
    }),
  },
  chama_details: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'inspect_only',
      scope: 'investigation',
      backendScope: 'investigation_only',
      sees: ['full chama profile', 'moderation metadata', 'system context'],
      does: ['Inspect or intervene only when platform policy requires it.'],
      tabs: ['Overview', 'Moderation', 'System Metadata'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'investigation',
      backendScope: 'platform_moderation',
      sees: ['chama overview', 'support and moderation data'],
      does: ['Review disputes and moderation cases.'],
      tabs: ['Overview', 'Support', 'Moderation'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['overview', 'members', 'finance summary', 'loans', 'meetings', 'policies', 'documents'],
      does: ['Edit the chama and open all core operations.'],
      tabs: ['Overview', 'Members', 'Finance', 'Governance', 'Policies', 'Documents'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['overview', 'finance tabs', 'contributions', 'loans', 'expenses', 'withdrawals'],
      does: ['Open finance operations and verify financial items.'],
      tabs: ['Overview', 'Finance', 'Contributions', 'Loans'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['overview', 'meetings', 'attendance', 'minutes', 'announcements', 'member participation'],
      does: ['Manage meeting records and post communications when allowed.'],
      tabs: ['Overview', 'Meetings', 'Attendance', 'Records', 'Announcements'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['broad read-only overview', 'finance history', 'governance history'],
      does: ['Inspect and review only.'],
      tabs: ['Overview', 'Finance', 'Governance', 'History'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['overview', 'rules', 'announcements', 'meetings', 'own obligations summary'],
      does: ['Open contributions, meetings, and announcements.'],
      tabs: ['Overview', 'Rules', 'Announcements', 'Meetings'],
    }),
  },
  members: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['cross-platform user and member data'],
      does: ['Investigate and moderate if needed.'],
      filters: ['role', 'status', 'risk'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_moderation',
      sees: ['support and moderated member data'],
      does: ['Support and moderate problem cases.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['full members table', 'statuses', 'roles', 'lifecycle state', 'member profiles'],
      does: ['Assign roles, suspend/remove, and inspect role history.'],
      tabs: ['List', 'Profile', 'Lifecycle', 'Role History'],
      quickActions: ['Assign role', 'Suspend member'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['members with finance columns', 'loan exposure', 'fine balance', 'contribution balance'],
      does: ['Inspect finance status only.'],
      tabs: ['List', 'Financial Profile'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['members with attendance and engagement context', 'participation profile'],
      does: ['Inspect attendance and communication readiness.'],
      tabs: ['List', 'Participation', 'Attendance'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['read-only member table', 'role history', 'status changes'],
      does: ['Audit and review only.'],
      tabs: ['List', 'Role History', 'Membership History'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'limited',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['limited members list', 'names', 'roles', 'basic public info'],
      does: ['View only.'],
      tabs: ['List', 'Public Details'],
    }),
  },
  contributions: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'inspect_only',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['platform contribution analytics when needed'],
      does: ['Inspect only.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['operational contribution data if support requires it'],
      does: ['Inspect and support only.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['group contribution overview', 'due and overdue items', 'member breakdown', 'compliance trends'],
      does: ['Monitor compliance and trigger follow-up actions.'],
      filters: ['due', 'overdue', 'paid'],
      quickActions: ['Open member breakdown', 'Review compliance'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['all contribution records', 'due/overdue queues', 'compliance dashboard'],
      does: ['Track unpaid items and export contribution reports.'],
      filters: ['member', 'status', 'period'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['limited compliance summaries for reminder support'],
      does: ['Support reminders and communication follow-up.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['read-only contribution reports and compliance history'],
      does: ['Audit only.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own due/overdue/paid contributions and details'],
      does: ['Pay contributions and view history.'],
      filters: ['due', 'overdue', 'paid'],
    }),
  },
  finance: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'inspect_only',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['platform finance health', 'cross-chama exposure', 'financial risk indicators'],
      does: ['Inspect finance posture and investigate operational risk.'],
      tabs: ['Overview', 'Transactions', 'Loans'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['issue-driven finance summaries', 'exceptions', 'support-relevant financial context'],
      does: ['Review finance issues and support escalations.'],
      tabs: ['Overview', 'Transactions'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['balances', 'compliance pressure', 'loan pipeline', 'expenses and withdrawals'],
      does: ['Oversee finance decisions and open core financial operations.'],
      tabs: ['Overview', 'Transactions', 'Loans'],
      quickActions: ['Loan queue', 'Expenses', 'Compliance', 'Reports'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['collections', 'liquidity', 'transaction history', 'loan pipeline', 'finance workload'],
      does: ['Run finance operations, verify movement, and manage follow-up queues.'],
      tabs: ['Overview', 'Transactions', 'Loans'],
      quickActions: ['Contribution intake', 'Withdrawals', 'Reconciliation', 'Reports'],
    }),
    [Role.SECRETARY]: exp({
      visible: false,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['little to no finance dashboard detail'],
      does: ['Use meetings and communication workspaces instead of finance operations.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['read-only balances', 'transaction trails', 'loan exposure', 'compliance indicators'],
      does: ['Review finance posture and inspect audit-relevant records.'],
      tabs: ['Overview', 'Transactions', 'Loans'],
    }),
    [Role.MEMBER]: exp({
      visible: false,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal money actions elsewhere in the app'],
      does: ['Use contributions, payments, and loans for self-service finance actions.'],
    }),
  },
  payments: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'inspect_only',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['platform payment metrics', 'provider-level issues'],
      does: ['Inspect provider and system payment problems.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['payment disputes and support-related payment views'],
      does: ['Support and escalate payment-related issues.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['payment overview for the chama', 'exceptions', 'selected payment details'],
      does: ['Inspect special cases when policy allows.'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['full payment tables', 'status and method filters', 'receipts', 'failures', 'verification queues'],
      does: ['Verify manual items and inspect failures.'],
      filters: ['status', 'method', 'member'],
      tabs: ['Overview', 'History', 'Verification', 'Failures'],
    }),
    [Role.SECRETARY]: exp({
      visible: false,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['little to no payment operational detail'],
      does: ['Usually no direct payment operations.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['read-only payment details', 'payment audit', 'receipt history'],
      does: ['Review only.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own payments, receipts, and status history'],
      does: ['Initiate payments, retry failures, and view receipts.'],
      tabs: ['History', 'Details', 'Receipts'],
    }),
  },
  loans: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'inspect_only',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['platform loan risk and default trends'],
      does: ['Inspect only.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['support or escalation loan cases if relevant'],
      does: ['Assist and escalate.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['loan portfolio summary', 'applications', 'overdue/defaulted items', 'recovery context'],
      does: ['Approve or reject where policy allows and review recovery actions.'],
      tabs: ['Portfolio', 'Applications', 'Overdue', 'Recovery'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['loan applications', 'active loans', 'repayment schedules', 'risk dashboard', 'guarantor exposure'],
      does: ['Review applications, approve finance-side steps, and manage recovery follow-up.'],
      tabs: ['Applications', 'Active', 'Repayments', 'Overdue', 'Risk'],
    }),
    [Role.SECRETARY]: exp({
      visible: false,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['little to no operational loan data'],
      does: ['Usually no direct loan operations.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['read-only loan details', 'defaults', 'recovery history', 'restructures'],
      does: ['Audit and review.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own eligibility', 'own loan request flow', 'own active loans', 'repayment schedule'],
      does: ['Request loans, choose guarantors if needed, repay, and view history.'],
      tabs: ['Eligibility', 'Request', 'Active', 'Schedule', 'History'],
    }),
  },
  meetings: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'inspect_only',
      scope: 'investigation',
      backendScope: 'investigation_only',
      sees: ['meeting records only when platform inspection requires it'],
      does: ['Inspect only.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'investigation',
      backendScope: 'platform_support',
      sees: ['meeting records in support or moderation contexts if needed'],
      does: ['Inspect only.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['meeting list/calendar', 'attendance', 'minutes', 'resolutions', 'quorum summary'],
      does: ['Create, edit, cancel meetings and oversee governance records.'],
      tabs: ['List', 'Calendar', 'Details', 'Records'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['meeting details relevant to finance decisions when needed'],
      does: ['Mostly view.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['meetings list/calendar', 'details', 'agenda', 'attendance', 'minutes', 'resolutions', 'reports'],
      does: ['Manage meetings end to end and record official meeting outputs.'],
      tabs: ['List', 'Calendar', 'Agenda', 'Attendance', 'Minutes', 'Resolutions', 'Reports'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['read-only meetings and governance records'],
      does: ['Review only.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['upcoming and past meetings', 'published agenda/minutes/resolutions'],
      does: ['Attend and view only.'],
      tabs: ['Upcoming', 'Past', 'Details'],
    }),
  },
  governance: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'inspect_only',
      scope: 'investigation',
      backendScope: 'investigation_only',
      sees: ['governance records only for platform review contexts'],
      does: ['Inspect only.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'investigation',
      backendScope: 'platform_support',
      sees: ['support or escalation governance records if needed'],
      does: ['Inspect only.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['motions list', 'motion details', 'results', 'archive', 'governance reports'],
      does: ['Create motions, manage voting, and finalize outcomes.'],
      tabs: ['Motions', 'Details', 'Results', 'Archive'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['motions relevant to finance or governance'],
      does: ['Vote if also participating as a member.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['motions list/details/results/archive'],
      does: ['Support governance records and manage details when permitted.'],
      tabs: ['Motions', 'Details', 'Results', 'Archive'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['governance archive', 'results', 'decision history'],
      does: ['Review only.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['active motions', 'motion details', 'results or archive when allowed'],
      does: ['Vote and view outcomes.'],
      tabs: ['Motions', 'Vote', 'Results'],
    }),
  },
  announcements: {
    [Role.SUPERADMIN]: exp({
      visible: false,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['platform broadcasts elsewhere, not regular chama announcements'],
      does: ['Use platform communication tools separately.'],
    }),
    [Role.ADMIN]: exp({
      visible: false,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['platform communication tools elsewhere'],
      does: ['Send platform communications where permitted.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['full announcements feed, details, create, and edit views'],
      does: ['Create, edit, publish, and pin announcements.'],
      tabs: ['Feed', 'Create', 'Edit', 'Details'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['announcement feed and details'],
      does: ['Usually read only.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['feed, details, create, and edit states'],
      does: ['Draft and post announcements where permitted.'],
      tabs: ['Feed', 'Create', 'Edit', 'Details'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['read-only announcements'],
      does: ['View only.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['announcement feed and details'],
      does: ['Read only.'],
    }),
  },
  notifications: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['operational notifications and platform failure queues'],
      does: ['Inspect failures in platform mode.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['operational notifications and support alerts'],
      does: ['Act on support and moderation alerts.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['personal and chama operational notifications', 'notification settings'],
      does: ['Open linked tasks and manage preferences.'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['finance alerts', 'verification alerts', 'settings'],
      does: ['Open finance tasks and manage preferences.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['meeting and communication reminders', 'details', 'settings'],
      does: ['Open linked tasks and manage reminder preferences.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['audit and compliance alerts', 'details', 'settings'],
      does: ['Open review items and manage preferences.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal notifications', 'details', 'settings'],
      does: ['Open linked items, mark read, and manage reminder preferences.'],
    }),
  },
  reports: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['global reports', 'platform analytics', 'billing and system reports'],
      does: ['Export and inspect platform reports.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['operational, support, and moderation reports'],
      does: ['Export and review operational reports.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['contributions, finance, loans, attendance, governance, and export tools'],
      does: ['Filter, export, and review operational performance.'],
      tabs: ['Contributions', 'Finance', 'Loans', 'Attendance', 'Governance'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['finance, payments, expenses, loans, and fines reports'],
      does: ['Generate and export finance-heavy reports.'],
      tabs: ['Finance', 'Payments', 'Expenses', 'Loans', 'Fines'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['attendance, meeting, and governance reports'],
      does: ['Generate and export meeting and governance reports.'],
      tabs: ['Attendance', 'Meetings', 'Governance'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['audit, compliance, finance, and governance reports'],
      does: ['Generate and export read-only oversight reports.'],
      tabs: ['Audit', 'Compliance', 'Finance', 'Governance'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal statements only'],
      does: ['View and download own statements.'],
      tabs: ['Contributions', 'Payments', 'Loans', 'Fines'],
    }),
  },
  profile: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own profile and platform role summary'],
      does: ['Edit profile and manage personal security settings.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own profile'],
      does: ['Edit profile and manage security settings.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own profile', 'chama roles summary', 'KYC status if applicable'],
      does: ['Edit profile and manage KYC or security settings.'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own profile and finance role summary'],
      does: ['Edit profile and manage security settings.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own profile and role summary'],
      does: ['Edit profile and manage security settings.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own profile and audit role summary'],
      does: ['Edit profile and manage security settings.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own profile', 'memberships', 'KYC state'],
      does: ['Edit profile, manage KYC, and update settings or security.'],
    }),
  },
  settings: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal app preferences'],
      does: ['Manage personal settings.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal preferences and operational alert settings'],
      does: ['Manage personal settings.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal settings and alert preferences'],
      does: ['Manage settings.'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal settings and finance alert preferences'],
      does: ['Manage settings.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal settings and reminder or communication preferences'],
      does: ['Manage settings.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal settings and review alert preferences'],
      does: ['Manage settings.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['notifications, privacy, appearance, and security preferences'],
      does: ['Manage settings.'],
    }),
  },
  support: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'support',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['platform support consoles elsewhere and personal support if needed'],
      does: ['Handle platform support operations in admin mode.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['tickets queue', 'disputes queue', 'details', 'resolution tools'],
      does: ['Resolve or escalate support cases.'],
      tabs: ['Tickets', 'Disputes', 'Resolution'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['chama-level disputes and tickets if permitted'],
      does: ['Review and resolve chama issues.'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['finance-related disputes or tickets when permitted'],
      does: ['Respond to finance issues.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'limited',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['communication or meeting-related issues when permitted'],
      does: ['Review and respond where allowed.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'read_only',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['issue history if needed'],
      does: ['Inspect only.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['own tickets or disputes only'],
      does: ['Create tickets/disputes and view updates.'],
      tabs: ['My Tickets', 'Create', 'Details'],
    }),
  },
  ai_assistant: {
    [Role.SUPERADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_all',
      sees: ['platform ops prompts and system analytics context'],
      does: ['Ask platform and system questions.'],
    }),
    [Role.ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'platform',
      backendScope: 'platform_support',
      sees: ['support and moderation prompts'],
      does: ['Ask operational questions.'],
    }),
    [Role.CHAMA_ADMIN]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['operational, governance, health, and compliance prompts'],
      does: ['Ask about approvals, risks, and chama health.'],
    }),
    [Role.TREASURER]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['finance, liquidity, payment, loan, and fine prompts'],
      does: ['Ask finance questions and get action suggestions.'],
    }),
    [Role.SECRETARY]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['meetings, attendance, and communication prompts'],
      does: ['Ask coordination questions.'],
    }),
    [Role.AUDITOR]: exp({
      visible: true,
      access: 'full',
      scope: 'chama',
      backendScope: 'scoped_chama',
      sees: ['audit and compliance prompts'],
      does: ['Ask review and compliance questions.'],
    }),
    [Role.MEMBER]: exp({
      visible: true,
      access: 'self_service',
      scope: 'personal',
      backendScope: 'own_records',
      sees: ['personal prompts for contributions, loans, and meetings'],
      does: ['Ask personal chama questions.'],
    }),
  },
};

export const getScreenExperience = (
  screen: AppScreenKey,
  role: Role
): ScreenRoleExperience => SCREEN_RBAC_MATRIX[screen][role];

export const canRoleAccessScreen = (screen: AppScreenKey, role: Role) =>
  SCREEN_RBAC_MATRIX[screen][role].visible;
